#!/bin/sh

set -e

MIRROR="http://ftp.de.debian.org/debian/"

lb config noauto \
   --architectures i386 \
   --ignore-system-defaults \
   --bootappend-live "boot=live components quiet splash persistence locales=de_DE.UTF-8 keyboard-layouts=de" \
   --checksums sha256 \
   --mode debian \
   --distribution stable \
   --initramfs-compression lzma \
   --iso-application "Gdi CD" \
   --iso-volume "Gdi CD" \
   --iso-publisher "Comnets Uni Bremen" \
   --parent-mirror-bootstrap ${MIRROR} \
   --parent-mirror-binary ${MIRROR} \
   --archive-areas "main contrib" \
   --apt apt \
        "${@}"
