<style type="text/css">
  body {
    background-color: #2f2f2f;
    color: white;
    max-width: 70em;
    margin: 0 auto;
  }

  h1 {
    font-size: 1.8em;
    margin-bottom: 0;
    text-decoration: underline;
    font-weight: 500;
  }

  h2 {
    font-size: 1.2em;
    margin: 0.1em 0.5em;
    font-weight: 500;
    color: rgba(255, 255, 255, 0.81);
  }

  h3 {
    margin: 0.1em 1em;
    font-weight: 500;
    color: rgba(255, 255, 255, 0.71);
  }

  p {
    margin-left: 1.5em;
    margin-right: 1em;
  }

  pre {
    background-color: #dae3cd;
    color: black;
    padding: 1em;
    margin: 0.8em 1.8em;
    border-radius: 0.5em;
    box-shadow: 0 0 1em rgba(0, 0, 0, 0.34);
  }

  p code {
    padding: 0.2em 0.4em;
    background-color: rgba(0, 0, 0, 0.27);
    border-radius: 0.5em;
  }
  
  a {
    color: cyan;
    text-decoration: none;
  }
  
  img {
    width: 256px;
    float: left;
    margin-right: 1em;
    box-shadow: 0 0 1em black;
    border-radius: 0.5em;
    margin-bottom: 1.5em;
  }

  video {
    width: 90%;
    margin: 1.5em 5%;
    box-shadow: 0 0 1em black;
  }

  .osdiverse {
    margin-top: 4em;
    padding: 0.5em;
    border: 1px solid rgba(0, 0, 0, 0.51);
    border-radius: 0.5em;
    background-color: rgba(255, 255, 255, 0.07);
    box-shadow: 0 0 1em rgba(0, 0, 0, 0.47);
  }

  .osdiverse > a {
    position: relative;
    top: -2em;
    left: 1em;
    padding: 0.3em;
    background-color: rgba(255, 255, 255, 0.33);
    border-radius: 0.3em 0.3em 0px 0px;
    color: black;
    margin: 0.5em;
  }

  .osdiverse > a:hover {
    text-decoration: underline;
  }
</style>

<script src="chooser.js">
</script>
